## [Problem 1] Matrix product is calculated manually

**QUESTION:**

A=\begin{bmatrix} -1 & 2 & 3 \\ Four & -Five & 6 \\ 7 & 8 & -9 \end{bmatrix},
B=\begin{bmatrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1 \end{bmatrix}


**Answer in steps**

**STEP 1:**

\begin{bmatrix}
(-1*0)+(2*0)+(3*2)&(-1*2)+(2*2)+(3*9)&(-1*1)+(2*-8)+(3*-1)\\
(4*0)+(-5*0)+(6*2)&(4*2)+(-5*2)+(6*9)&(4*1)+(-5*-8)+(6*-1)\\
(7*0)+(8*0)+(-9*2)&(7*2)+(8*2)+(-9*9)&(7*1)+(8*-8)+(-9*-1)\\
\end{bmatrix},



**STEP 2:**

\begin{bmatrix}
(O+0+6)&(-2+4+27)&(-1-16-3)\\
(O+0+12)&(8-10+54)&(4+40-6)\\
(O+0-18)&(14+16-81)&(7-64+9)\\
\end{bmatrix},


**FINAL ANSWER**

\begin{pmatrix} 
6&29&-20\\
12&52&38\\
-18&-51&-48
\end{pmatrix}


## [Problem 2] Calculation by NumPy function

In [6]:
import   numpy   as  np
ndarray_A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
ndarray_B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
ndarray_A_B = np.matmul(ndarray_A,ndarray_B)
print(ndarray_A_B)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## [Problem 3] Implementation of calculation of a certain element

In [28]:
Sum = (ndarray_A[1][0]*ndarray_B[0][1])+(ndarray_A[1][1]*ndarray_B[1][1])+(ndarray_A[1][2]*ndarray_B[2][1])
Sum

52

## [Problem 4] Creating a function that performs matrix multiplication

In [31]:
def product_of_matrix(a, b):
    ndarray_A_B = np.empty([3,3])
    for row in range(a.shape[0]):
        for column in range(b.shape[1]):
            ndarray_A_B[row][column] = sum(a[row, :]*b[:, column])
    return ndarray_A_B
print(product_of_matrix(ndarray_A, ndarray_B))


[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


## [Problem 5] Judge the input whose calculation is not defined

In [37]:
d_ndarray = np.array([[-1, 2, 3],[4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7],[6, -5, 4]])
if(d_ndarray.shape[0]==e_ndarray.shape[1]):
    print(product_of_matrix(d_ndarray, e_ndarray))
else:
        print("Incorrect of matrix shape please make sure the row's shape of matrix A is equal to the column's shape of matrix B in multprication")

Incorrect of matrix shape please make sure the row's shape of matrix A is equal to the column's shape of matrix B in multprication


## [Problem 6] Transposition

In [36]:
f = d_ndarray.T
print(product_of_matrix(f, e_ndarray))

[[ 33. -28.   9.]
 [-48.  41.  -6.]
 [  9.  -6.  45.]]
